### ISSUE TITLE
error compiling with mingw

### ISSUE THREAD

**Issue by clintr-at-kornak** [jedisct1/libhydrogen#42]
Hello, I've been trying to compile with mingw (gcc version is 4.8.1) on Windows 7 64-bit.
"make lib" works, but for "make all" I get the error "undefined reference to `SystemFunction036@8'".  I get the same error if I try to compile libhydrogen.a into a program of my own.
Can you tell me how to correct this?
Thanks

**Comment by clintr-at-kornak** [comment]
I've just tried updating to latest mingw (gcc version 8.2.0).  Problems are the same.  (I also had to put a blank line at the start of the makefile or make complained "make: cc: Command not found" - see https://stackoverflow.com/questions/36232323/mingw-make-cc-command-not-found).

**Comment by jedisct1** [comment]
You should set the environment variable `CC` to the C compiler you want to use.

For example:

```
CC=x86_64-w64-mingw32-gcc
```

**Comment by clintr-at-kornak** [comment]
Hello, thank you for the solution to the mingw make error.  However, it does not solve my original problem, which is that I get the error "undefined reference to `SystemFunction036@8'".

**Comment by jedisct1** [comment]
Have you tried with msys2?
